version: "2.1"
services:
  samba:
    image: dperson/samba
    container_name: samba
    volumes:
      - /media/sdb:/mount/sdb
      - /media/sdc:/mount/sdc
      - /media/nvme1n1p1:/mount/nvme1n1p1
    environment:
      - PUID=1000
      - PGID=1000
      - WORKGROUP=workgroup
      - USER=jeffrey;1234
      - SHARE=sdb;/mount/sdb;yes;no;no;jeffrey;none;none;sdb
      - SHARE2=sdc;/mount/sdc;yes;no;no;jeffrey;none;none;sdc
      - SHARE3=nvme1n1p1;/mount/nvme1n1p1;yes;no;no;jeffrey;none;none;nvme1n1p1
      - PERMISSIONS
      - SMB
    ports:
      - 139:139
      - 445:445
      - 137:137/udp
      - 138:138/udp
    restart: unless-stopped

